[theme]
primaryColor = "#3949AB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F6FA"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 25

[browser]
gatherUsageStats = false
